#INCLUDE <P16F84A.INC>
       ORG 0X0
       BSF STATUS, 0X05 ; VAI AO BANCO 1
       BSF TRISB, 0X00 ; RB0 COMO ENTRADA
       BCF TRISA, 0X00 ; RA0 COMO SAÍDA
       BCF STATUS, 0X05 ; VAI AO BANCO 0
       MOVLW 0X01 ; MARCAR A POSIÇÃO DO LED NO PORTA
       BCF PORTA, 0X00 ; APAGA LED
TEST1  BTFSC PORTB, 0X00 ; TESTA A BOTOEIRA
       GOTO TEST1 ; BOTOEIRA NÃO PRESSIONADA, NADA A FAZER
       XORWF PORTA, 0X01 ; BOTOEIRA PRESSIONADA INVERTE LED
TEST2  BTFSS PORTB, 0X00 ; TESTA BOTOEIRA
       GOTO TEST2 ;BOTOEIRA PRESSIONADA, NADA A FAZER
       GOTO TEST1 ;BOTOEIRA SOLTA, VOLTAR AO INICIO
END